---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu24.04
    image: antmelekhin/docker-systemd:ubuntu-24.04
  - name: debian13
    image: antmelekhin/docker-systemd:debian-13
  - name: rocky10
    image: antmelekhin/docker-systemd:rockylinux-10
provisioner:
  name: ansible
ansible:
  playbooks:
    create: create.yml
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
    destroy: destroy.yml
  cfg:
    defaults:
      interpreter_python: auto_silent
scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
