---
- name: Prepare target containers
  hosts: molecule
  gather_facts: true
  tasks:
    - name: Wait for Elasticsearch
      ansible.builtin.uri:
        url: http://elasticsearch:9200
        status_code: 200
        timeout: 5
      register: elasticsearch_status
      retries: 30
      delay: 5
      until: elasticsearch_status.status | default(0) == 200
