name: Integration Tests
on:
  pull_request:
    branches: [main]
    paths:
      - "tests/integration/**"
      - "plugins/**"
      - ".github/workflows/ansible-test-integration.yml"
  push:
    branches: [dev]
    paths:
      - "tests/integration/**"
      - "plugins/**"
      - ".github/workflows/ansible-test-integration.yml"

jobs:
  ansible-test:
    runs-on: ubuntu-latest
    env:
      owner: zupersero

    strategy:
      fail-fast: false
      matrix:
        elastic: ["9.2.0"]
        ansible_core: ["v2.19.5"]
        python_version: ["3.11"]
    steps:
      - name: Get elasticsearch
        run: curl -fsSL https://elastic.co/start-local | ES_LOCAL_PASSWORD="changeme" sh -s -- -v ${{ matrix.elastic }}

      - name: Wait for Elasticsearch
        run: |
          set -euo pipefail
          for i in {1..15}; do
          if curl -fsS -u "elastic:changeme" "http://localhost:9200/_cluster/health" | grep -qE '"status":"(green|yellow)"'; then
              echo "Elasticsearch is ready."
              exit 0
          fi
          echo "Waiting for Elasticsearch... ($i/15)"
          sleep 5
          done
          echo "Elasticsearch did not become ready after 15 attempts."
          exit 1

      - name: Wait for Kibana
        run: |
          set -euo pipefail
          for i in {1..15}; do
          if curl -fsS -u "elastic:changeme" -H "kbn-xsrf: true" "http://localhost:5601/api/status" | grep -q '"level":"available"'; then
              echo "Kibana is ready."
              exit 0
          fi
          echo "Waiting for Kibana... ($i/15)"
          sleep 5
          done
          echo "Kibana did not become ready after 15 attempts."
          exit 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core==${{ matrix.ansible_core }} ansible-lint coverage==7.6.1 passlib


      - name: Make test directory
        run: mkdir -p ansible_collections/zupersero/kibana

      - uses: actions/checkout@v4
        with:
          path: ansible_collections/zupersero/kibana
      - name: Install collection dependencies
        working-directory: ansible_collections/zupersero/kibana
        run: ansible-galaxy collection install .

      - name: Run integration tests
        working-directory: ansible_collections/zupersero/kibana
        run: |
          ansible-test integration --coverage

      - name: Generate coverage report
        working-directory: ansible_collections/zupersero/kibana
        run: |
          ansible-test coverage combine
          coverage xml --data-file=tests/output/coverage/coverage --include=plugins/*

      - name: Coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ansible_collections/zupersero/kibana/coverage.xml
          format: markdown
          output: both
          badge: true
